#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Werewolf GRPO Training Reward Function.

Based on the Stackelberg competition method:
- Impact Measurement: computes the influence of leader utterances on follower response probabilities
- Reward: R(u_t) = sum log P_F(desired | context + u_t) - sum log P_F(undesired | context + u_t)

Calls the local reward_server to compute rewards.
"""

import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry
import os
from typing import List, Dict, Any, Optional

# Default reward value (used when API call fails)
DEFAULT_REWARD_VALUE = 0.0

# Reward Server configuration
REWARD_SERVER_HOST = os.environ.get('REWARD_SERVER_HOST', '127.0.0.1')
REWARD_SERVER_PORT = os.environ.get('REWARD_SERVER_PORT', '8000')
REWARD_SERVER_URL = f'http://{REWARD_SERVER_HOST}:{REWARD_SERVER_PORT}'

# Configure requests session
session = requests.Session()
adapter = HTTPAdapter(
    pool_connections=10,
    pool_maxsize=10,
    max_retries=Retry(total=3, backoff_factor=1, status_forcelist=[500, 502, 503, 504])
)
session.mount('http://', adapter)

# Leader response placeholder (consistent with convert_logs_to_grpo_data.py)
LEADER_RESPONSE_PLACEHOLDER = "{{LEADER_RESPONSE}}"

# Length penalty configuration
# Linear penalty starts beyond LENGTH_PENALTY_MIN_WORDS; full penalty at LENGTH_PENALTY_MAX_WORDS
LENGTH_PENALTY_MIN_WORDS = 100
LENGTH_PENALTY_MAX_WORDS = 200
LENGTH_PENALTY_MAX = 10.0  # Max additive penalty (additive to avoid sign issues with multiplicative decay)


def my_reward_function(
    data_sources: List[str],
    solution_strs: List[str],
    ground_truths: List[str],
    extra_infos: Optional[List[Dict[str, Any]]] = None,
    **kwargs,
) -> List[float]:
    """
    Compute persuasive impact reward for leader utterances in Werewolf.
    
    R(u_t) = sum log P_F(desired | context + u_t) - sum log P_F(undesired | context + u_t)
    
    Args:
        data_sources: List of data source identifiers.
        solution_strs: List of leader utterances generated by the model.
        ground_truths: Follower's actual responses (unused; reward is probability-based).
        extra_infos: List of dicts, each containing:
            - follower_prompt_template: Follower's prompt template (messages format).
            - intent_identification: Dict with desired_responses and undesired_responses.
        **kwargs: Additional arguments.
    
    Returns:
        List[float]: Reward value for each leader utterance.
    """
    if extra_infos is None:
        extra_infos = [{} for _ in range(len(solution_strs))]
    
    # Build request payload
    requests_payload = []
    for i in range(len(solution_strs)):
        extra_info = extra_infos[i] or {}
        
        # Get follower's prompt template
        follower_prompt_template = extra_info.get('follower_prompt_template', [])
        
        # Get intent identification (desired and undesired responses)
        intent_identification = extra_info.get('intent_identification', {})
        desired_responses = intent_identification.get('desired_responses', [])
        undesired_responses = intent_identification.get('undesired_responses', [])
        
        requests_payload.append({
            'leader_response': solution_strs[i],
            'follower_prompt_template': follower_prompt_template,
            'desired_responses': desired_responses,
            'undesired_responses': undesired_responses,
        })
    
    # Call reward server
    url = f'{REWARD_SERVER_URL}/compute_reward'
    
    try:
        resp = session.post(url, json={'requests': requests_payload}, timeout=6000)
        if resp.status_code == 200:
            data = resp.json() or {}
            rewards = data.get('rewards', None)
            if not isinstance(rewards, list) or len(rewards) != len(solution_strs):
                print(f'[Reward API Warning] Invalid response format, using default values')
                rewards = [DEFAULT_REWARD_VALUE for _ in range(len(solution_strs))]
        else:
            print(f'[Reward API Error] Status: {resp.status_code}, Response: {resp.text}')
            rewards = [DEFAULT_REWARD_VALUE for _ in range(len(solution_strs))]
    except Exception as e:
        print(f'[Reward API Exception] {e}')
        rewards = [DEFAULT_REWARD_VALUE for _ in range(len(solution_strs))]
    
    # Post-processing: ensure rewards are within reasonable range, and apply length penalty
    final_rewards = []
    for i, reward in enumerate(rewards):
        try:
            reward = float(reward)
        except (ValueError, TypeError):
            reward = DEFAULT_REWARD_VALUE
        
        # Clamp reward to avoid numerical instability
        reward = max(-50.0, min(50.0, reward))
        
        # Length penalty: penalize overly long leader utterances
        word_count = len(solution_strs[i].split())
        if word_count > LENGTH_PENALTY_MIN_WORDS:
            if word_count >= LENGTH_PENALTY_MAX_WORDS:
                penalty = -LENGTH_PENALTY_MAX
            else:
                # Linear interpolation from 0 to -LENGTH_PENALTY_MAX
                penalty = -LENGTH_PENALTY_MAX * (word_count - LENGTH_PENALTY_MIN_WORDS) / (LENGTH_PENALTY_MAX_WORDS - LENGTH_PENALTY_MIN_WORDS)
            reward += penalty
        
        final_rewards.append(reward)
    
    return final_rewards


def compute_single_reward(
    leader_response: str,
    follower_prompt_template: List[Dict[str, str]],
    desired_responses: List[str],
    undesired_responses: List[str],
) -> float:
    """
    Compute reward for a single leader utterance (for debugging and testing).
    
    Args:
        leader_response: The leader's utterance.
        follower_prompt_template: Follower's prompt template.
        desired_responses: List of desired follower responses.
        undesired_responses: List of undesired follower responses.
    
    Returns:
        float: Reward value.
    """
    rewards = my_reward_function(
        data_sources=['custom_api'],
        solution_strs=[leader_response],
        ground_truths=[''],
        extra_infos=[{
            'follower_prompt_template': follower_prompt_template,
            'intent_identification': {
                'desired_responses': desired_responses,
                'undesired_responses': undesired_responses,
            }
        }]
    )
    return rewards[0]


if __name__ == '__main__':
    # Simple test
    import json
    
    # Load test data
    test_data_path = 'test_output.jsonl'
    
    try:
        with open(test_data_path, 'r', encoding='utf-8') as f:
            test_sample = json.loads(f.readline().strip())
        
        extra_info = test_sample.get('extra_info', {})
        
        # Test leader response
        test_leader_response = "I think player 3 has been acting very suspiciously."
        
        reward = compute_single_reward(
            leader_response=test_leader_response,
            follower_prompt_template=extra_info.get('follower_prompt_template', []),
            desired_responses=extra_info.get('intent_identification', {}).get('desired_responses', []),
            undesired_responses=extra_info.get('intent_identification', {}).get('undesired_responses', []),
        )
        
        print(f'Test Leader Response: {test_leader_response}')
        print(f'Reward: {reward}')
        
    except FileNotFoundError:
        print(f'Test data file not found: {test_data_path}')
    except Exception as e:
        print(f'Test failed: {e}')
